// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa_Imeeh2rd_-Z-YHtspt4ELwQbswOx9w',
    appId: '1:994777197952:web:1c280ad836fd50824a6565',
    messagingSenderId: '994777197952',
    projectId: 'exambuddy-64399',
    authDomain: 'exambuddy-64399.firebaseapp.com',
    storageBucket: 'exambuddy-64399.appspot.com',
    measurementId: 'G-JPQ423YFS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWearaCF52lcVHF4POOiBDxncfhsZPMYQ',
    appId: '1:994777197952:android:13fe839ee1b323cd4a6565',
    messagingSenderId: '994777197952',
    projectId: 'exambuddy-64399',
    storageBucket: 'exambuddy-64399.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByeogjw8rmj38O5lR-YiZdx0-LhhwjDjA',
    appId: '1:994777197952:ios:c4e75c6a01e317724a6565',
    messagingSenderId: '994777197952',
    projectId: 'exambuddy-64399',
    storageBucket: 'exambuddy-64399.appspot.com',
    iosClientId: '994777197952-jk8a9egp8cp5sbtehsipg16cjnr51grt.apps.googleusercontent.com',
    iosBundleId: 'com.example.examBuddy',
  );
}
